### ISSUE TITLE
Table names created from entity description instead of entity names in the config file

### ISSUE THREAD

**Issue by eomwandho** [gltn/stdm#101] opened 2016-07-09 06:44 UTC
@gkahiu and @pgathogo. I'm working on upgrading old configuration file to the new configuration based on .stc file extension. Now, since the upgrade will be done in the background, stdm configuration schema updater will not be run directly by the user, but instead run in the background by executing [ConfigurationSchemaUpdater.exec_()](https://github.com/gltn/stdm/blob/ref_config_mod/data/configuration/config_updater.py#L71), after loading the configuration.stc to STDM configuration instance. Now, the issue I'm facing is that by calling ConfigurationSchemaUpdater.exec_() directly instead of running it through the configuration wizard, the table names are created from description of entity element instead of name. What could be the issue?

![tables names screen shot](https://cloud.githubusercontent.com/assets/2696951/16706535/259ce60c-45b9-11e6-9521-963076ec6181.png)

Here is my [configuration.stc](https://gist.github.com/eomwandho/5a3a516541d96db4d4f65d616e34cccc)

**Comment by gkahiu** [comment] 2016-07-09 11:23
Hi Eric,

The issue is brought about because you are using the description in the short name attribute. Entities are actually constructed using the short name rather than name. So please adjust your code so that the entity names are inserted in the short name tag. Short name can include uppercase and spaces, the system then automatically normalizes the name by appending the profile prefix and converting the name to lowercase and removing spaces.

I hope this makes sense.

Cheers

**Comment by eomwandho** [comment] 2016-07-09 11:34
Hi John,

I have seen your point, let me fix it and revert. Thanks

Cheers

**Comment by eomwandho** [comment] 2016-07-11 11:00
@gkahiu 

I get the following [error](https://gist.github.com/eomwandho/0957dd2e336dd4d01bae3dba6a95f177), my new stc file looks okay. [configuration.stc](https://gist.github.com/eomwandho/c6803ed702bd318ff4d432712df91fa8)

**Comment by gkahiu** [comment] 2016-07-11 11:46
Dear Eric,

Please critically review the configuration file especially items under the
*Relations* tag; I have noticed a couple of issues some of which are, but
not limited to:

   - Parent tag attribute is invalid, I doubt there is a table called
*import_spatial
   unit* - *<EntityRelation child="social_tenure_relationship"
   parent="import_spatial_unit" parentColumn="id"
   name="fk_ba_import_spatial_unit_id_ba_social_tenure_relationship_import_spatial_unit_id"
   childColumn="import_spatial_unit_id"/>*
   - Child tag attribute is invalid, similarly there is no table by the
   name *import_party_supporting_document* - *<EntityRelation
   child="import_party_supporting_document"
   parent="check_import_party_document_type" parentColumn="id"
   name="fk_ba_check_import_party_document_type_id_ba_import_party_supporting_document_document_type"
   childColumn="document_type"/>*
   - Party and Spatial_Unit entities do not support documents from the
   previous migration hence, the tag value for *supportsDocuments* for
   Party and Spatial Unit should be false.

Please review how the entity relations are created then retest.

Regards,

John

**Comment by eomwandho** [comment] 2016-07-11 13:03
Hi John,

Here is updated [config](https://gist.github.com/eomwandho/4b0bfbf8448a71b69d28015f6d70e21a) file still throwing same error.

**Comment by eomwandho** [comment] 2016-07-11 13:07
The last few lines of the log file

`
16-07-11 15:48:46,141 - stdm - DEBUG - fk_ba_check_tenure_type_id_ba_social_tenure_relationship_tenure_type foreign key constraint successfully created.
2016-07-11 15:48:46,152 - stdm - DEBUG - fk_ba_party_id_ba_social_tenure_relationship_party_id foreign key constraint successfully created.
2016-07-11 15:48:46,163 - stdm - DEBUG - fk_ba_spatial_unit_id_ba_social_tenure_relationship_spatial_unit_id foreign key constraint successfully created.
2016-07-11 15:48:46,163 - stdm - DEBUG - Checking if ba_vw_social_tenure_relationship view exists...
2016-07-11 15:48:46,168 - stdm - DEBUG - Creating STR: Getting parent for party_id column
2016-07-11 15:48:46,168 - stdm - DEBUG - Parent found
2016-07-11 15:48:46,168 - stdm - DEBUG - Creating STR: Getting parent for spatial_unit_id column
2016-07-11 15:48:46,168 - stdm - DEBUG - Parent found
2016-07-11 15:48:46,168 - stdm - DEBUG - Creating STR: Getting parent for tenure_type column
2016-07-11 15:48:46,168 - stdm - DEBUG - Parent found
2016-07-11 15:48:46,171 - stdm - DEBUG - Creating STR: Getting parent for gender column
`

**Comment by eomwandho** [comment] 2016-07-11 13:11
Probably the error has something to do with the way gender is being parsed and set on the entity relations

**Comment by gkahiu** [comment] 2016-07-11 13:24
You are right, the configuration information does not specify a relation
that links the gender lookup to the sex column in the party table i.e.
there is a missing relation linking the two.

Also, do not include the following entities in the configuration since they
are automatically implied and created by the system, these are (short
names):

   1. supporting_document
   2. social_tenure_relationship
   3. str_relations

This is because each profile automatically contains tables for managing
social tenure relationships and supporting documents.

Regards.

**Comment by eomwandho** [comment] 2016-07-11 18:08
If an entity has attribute supportsDocuments set to false, like in the case of the old configuration file entities, does it mean that it should not have an <EntityRelation child="party_supporting_document" ..../> node?

**Comment by gkahiu** [comment] 2016-07-11 18:35
Am not sure about your question but let me try to answer it by highlighting
the logic behind supporting documents in the configuration:

   1. When a new profile is created, by default it creates 2 entities in
   the background (i.e. not visible to the user). These are
   supporting_document and social_tenure_relationship (both with the prefix
   appended).
   2. So when a user creates a new entity that supports documents, then an
   association table that links to both the primary and supporting_document
   tables respectively, is created.
   3. Similarly, the social_tenure_relationship has an association table
   (named social_tenure_relationship_supporting_document) that links it to the
   supporting_document base table.
   4. Taking this into consideration, then it means that there is no need
   for explicitly defining supporting_document, str_relations and
   social_tenure_relationship tables in the configuration.
   5. Also, when supportsDocuments is set to False for party and
   spatial_unit then it means that the association table for supporting
   documents for these respective entities will not be created.
   6. In summary, there is no additional node for an entity's supporting
   documents. To enable/disable it, then just set the supportsDocuments flag
   in the primary entity to True/False.

I hope this answers your question.

Regards,

John

**Comment by eomwandho** [comment] 2016-07-13 03:56
Hi John,

My question above didn't include the xml node, as shown now. But, any way, [this is](https://gist.github.com/eomwandho/f8c649c4636f016aabf7dbef098b49eb) the output based on your comments.

Quick question? Even if entities in the old configuration didn't have support for documents, what will be the harm of including them in the upgrade to the new .stc file extension?

**Comment by gkahiu** [comment] 2016-07-13 05:37
Hi Eric,

   - Have you tested the new stc file to confirm that it is working?
   - As for supporting documents, there is no harm or side effect but the
   intention is to restore the user to a similar state as was in the previous
   configuration then they can choose what to upgrade/incorporate by
   re-running the wizard. If they do wish, then they can also choose to enable
   supporting documents for party and spatial unit entities and for this I
   would rather they do it explicitly via the configuration wizard.

Regards,

John

**Comment by wondie** [comment] 2016-08-28 09:43
This issue is now fixed.

**Closed by wondie** 2016-08-28 09:43 UTC
