### ISSUE TITLE
Spatial Entity Double Click

### ISSUE THREAD

**Issue by nkoech** [gltn/stdm#154] opened 2016-08-08 12:08 UTC
This happens when you try to double click on a record in the spatial entity while the base layer (raster) is selected in the layer panel.

```
TypeError: QgsHighlight(QgsMapCanvas, QgsGeometry, QgsVectorLayer): argument 3 has unexpected type 'QgsRasterLayer' 
Traceback (most recent call last):
  File "C:/Users/nkoech/.qgis2/python/plugins\stdm\ui\entity_browser.py", line 996, in on_select_attribute
    self.record_feature_highlighter(record_id)
  File "C:/Users/nkoech/.qgis2/python/plugins\stdm\ui\entity_browser.py", line 1024, in record_feature_highlighter
    geom_wkb
  File "C:/Users/nkoech/.qgis2/python/plugins\stdm\ui\entity_browser.py", line 1038, in highlight_geom
    map_canvas, qgis_geom, layer
TypeError: QgsHighlight(QgsMapCanvas, QgsGeometry, QgsVectorLayer): argument 3 has unexpected type 'QgsRasterLayer'
```

**Comment by gkahiu** [comment] 2016-08-08 12:22
@wondie, check that the selected (active) layer is indeed the correct STDM layer.

**Comment by wondie** [comment] 2016-08-08 16:16
@gkahiu  and @nkoech I will fix and report back.

**Comment by nkoech** [comment] 2016-08-08 18:34
@wondie I looked at it briefly and implemented a short method shown below that can be called in  **record_feature_highlighter** method. The return of this method would then be passed to **self.highlight_geom()** method as active layer. The layer_type being 0 for a vector layer. It works perfectly on my side.

```
    def set_active_layer(self, layer_type):
        """
        Sets active layer.
        :param layer_type: layer identifier
        :type layer_type: Integer 
        :return: layer
        :rtype: layer
        """
        layers = iface.mapCanvas().layers()
        for l in layers:
            if l.type() == layer_type:
                if l != iface.activeLayer():
                    iface.setActiveLayer(l)
                    return l
                else:
                    return l
```

**Comment by wondie** [comment] 2016-08-08 18:48
@nkoech thank you very much for the method and explanation. I have one question. What if the user has added another vector layer?
I have also done some modification to in spatial_unit_manager.py to fix the issue and it is working.

**Comment by nkoech** [comment] 2016-08-08 20:09
@wondie thanks for the update. Although it seems to fail in the following circumstance; It works even when the STDM layer is unchecked in the layer panel. Probably you should fall back to using _iface.activeLayer()_ instead of _QgsMapLayerRegistry.instance()_ which  returns all layers (checked and unchecked). 

Potentially the most effective way could be by comparing layer names in the layer panel to the layer name in the Spatial Unit Manger window and subsequently making the match the active layer.

**Comment by wondie** [comment] 2016-08-08 20:22
That is true. But if the user has unchecked a layer, it means he is not interested in seeing the layer ;D In this case what happens is, it  will still highlight the feature with the layer being visible. 

As you have said, the layer name comes from spatial unit manager. 

```
 sel_lyr_name = self.sp_unit_manager. \
                    geom_col_layer_name(
                    self._entity.name, geom
                )
```

**Comment by nkoech** [comment] 2016-08-08 21:07
@wondie thanks man. I had not realized that the line you mentioned above was returning the layer name as captured in the Spatial Unit Manager QComboBox

**Comment by wondie** [comment] 2016-08-08 21:15
@nkoech you are most welcome. The issue is not fixed with this commit. Please confirm if it is working. I have also fixed the view STR search issue on lookups.

**Comment by nkoech** [comment] 2016-08-08 22:18
@wondie sure, I am going to test your new commit and get back to you. Could you also look at this new implementation and let me know what you think
```
    def record_feature_highlighter(self, record_id):
        """
        Highlights a feature of a record.
        :param record_id: The id of a row
        :type record_id: Integer
        :return: None
        :rtype: NoneType
        """
       .
       .
       .
       .
       .
       .      
                stdm_active_vector = self.set_active_layer(sel_lyr_name)
                if stdm_active_vector:
                    self.highlight_geom(
                        iface.mapCanvas(),
                        stdm_active_vector,
                        geom_wkb
                    )

    def set_active_layer(self, layer_name):
        """
        sets active layer.
        :param layer_name: name of selected layer
        :type layer_type: string
        :return: layer
        :rtype: layer
        """
        layers = iface.mapCanvas().layers()
        if layers:
            for lyr in layers:
                if lyr.name() == layer_name:
                    if lyr != iface.activeLayer():
                        iface.setActiveLayer(l)
                        return lyr
                    else:
                        return lyr
```

**Comment by wondie** [comment] 2016-08-09 05:23
@nkoech that is good. It works in different situations.

**Comment by nkoech** [comment] 2016-08-10 22:07
@wondie sorry I forgot to let you know that I test your new commit and it works perfectly. It never raised any exception with all the tests I threw at it.

**Comment by wondie** [comment] 2016-08-11 07:58
@nkoech Thank you for the test. If the issue is fixed, please close it.

**Closed** 2016-08-11 10:33 UTC
Labels: bug
