### ISSUE TITLE
Error on log in where the current profile is invalid or empty

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#120] opened 2016-07-13 20:08 UTC
If a user tries to log into the system in the case where the value of the **CurrentProfile** key (in the registry) is empty or does not exist in the loaded configuration, then the system raises an error because it tries to load entities for a non-existing profile. For example, if the string value of CurrentProfile is _Informal_ and I try to load a configuration which does not contain any profile called Informal, then the system raises an exception.

I have traced this to the following piece of code in _plugin.py_ (from line 300):
```
self.current_profile = current_profile()
self.loadModules()
self._user_logged_in = True
self.default_profile()
```

In the snippet above, `self.loadModules()` will try to load entities where `self.current_profile is None` thereby raising the error. 

Recheck the logic.

**Comment by wondie** [comment] 2016-07-14 01:54
Thank you for the clarification of the problem. I fixed the issue with [this commit](https://github.com/gltn/stdm/commit/556949e5a579a0a4981b3f13ba20226253a5ca23). The [current profile check](https://github.com/gltn/stdm/commit/556949e5a579a0a4981b3f13ba20226253a5ca23#diff-66c71ea3faaa52c277917c951aa67921R301) is now done before loading the modules which was supposed to be like that. 

I also notice that there is a configuration.stc file in the template folder of the plugin directory but it didn't load in the list of profile under options and the wizard. It only listed my old configuration. Is that ok?

**Comment by gkahiu** [comment] 2016-07-14 05:47
Thanks for fixing this.

As for the configuration file in the template folder, it will be the
default configuration for a clean installation. Since you already had a
configuration.stc in the .stdm folder, then this one was not copied. The
scenarios are as follows:

   1. If there is no configuration.stc and stdmConfig.xml in the .stdm
   folder then the configuration.stc (in the templates folder) will be copied;
   2. If there is stdmConfig.xml and no configuration.stc then the
   migration module will attempt to create a new configuration.stc from the
   old stdmConfig.xml configuration file;
   3. If there is a configuration.stc file, then the default configuration
   will not be copied.

I hope this is clear.

Regards.

**Comment by wondie** [comment] 2016-07-14 14:31
You are welcome. That is well noted. 

But why did the current profile became none when loading the configuration.stc in the template folder? It is not an issue now but I am not sure how it happened, even though it helped us find an issue.

**Comment by wondie** [comment] 2016-07-14 15:17
The issue is now fixed by [this commit.] There will be no side effects. (https://github.com/gltn/stdm/commit/d5a8fc0b47f868d54a179d90ebf6cec90fd0c3ee)

**Closed** 2016-07-16 09:17 UTC
Labels: bug
