### ISSUE TITLE
Failure to create profile using design forms wizard when deleting a table

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#56] opened 2016-05-06 16:26 UTC
When I tried to create a profile on top of the existing profile, on the last page, even though the result shows success message, it shows a python error too. 

No new profile is added on configuration.stc and no database table is created for the profile.

Below is the full error message. 

An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\ui\wizard\wizard.py", line 372, in _updater_thread_started
    self.config_updater.exec_()
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\configuration\config_updater.py", line 93, in exec_
    self.update_profile(p)
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\configuration\config_updater.py", line 133, in update_profile
    status = er.drop_foreign_key_constraint()
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\configuration\entity_relation.py", line 148, in drop_foreign_key_constraint
    return self.constraint_deleter()
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\configuration\entity_relation_updater.py", line 120, in drop_foreign_key_constraint
    fk_cons = foreign_key_constraint(entity_relation)
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\configuration\entity_relation_updater.py", line 81, in foreign_key_constraint
    return ForeignKeyConstraint([child_col_attr], [parent_col_attr])
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\migrate\changeset\constraint.py", line 114, in __init__
    **kwargs)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\sql\schema.py", line 2543, in __init__
    **self.dialect_kwargs
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\sql\schema.py", line 1474, in __init__
    "expected, got %r" % self._table_column)
ArgumentError: String, Column, or Column-bound argument expected, got None

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.8.3-Wien Wien, exported

Python path: ['C:/Users/Wondim/.qgis2/python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python', u'C:/Users/Wondim/.qgis2/python', u'C:/Users/Wondim/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\python_dateutil-2.1-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/Wondim/.qgis2//python', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\stdm\\third_party', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\stdm\\third_party\\fontTools']

**Comment by gkahiu** [comment] 2016-05-23 12:44
Fixed in this commit  [91f5794](https://github.com/gltn/stdm/commit/91f5794e7513322cf84abd1afc26eede8c2bf96e). Please confirm.

**Comment by wondie** [comment] 2016-05-24 22:08
When I create a new profile on top of the existing one, STDM and QGIS hangs and stops working. I don't know if the issue is related to this one.

**Comment by gkahiu** [comment] 2016-05-25 06:04
I remember previously experiencing this while testing changes in profiles, and what I noticed is that if there are foreign key constraints that were not fully deleted in a previous configuration update process, then the database would be in an unstable state. 

Please try the following:
1. Drop the database
2. Recreate a new one 
3. Repeat the profile creation process

Let me know if this resolves your issue.

**Comment by wondie** [comment] 2016-05-25 06:12
So does this mean it is not possible to have more than one profile? My objective was to have two profiles.

**Comment by gkahiu** [comment] 2016-05-25 06:19
What am saying is that you might be working with a previously corrupted/unstable state database because of the previous configuration implementation but recreating it should resolve it. So please confirm if recreating a new database enables you to have even five profiles.

**Comment by wondie** [comment] 2016-05-25 12:23
Ok, when I re-run the wizard after making changes in the database, the wizard and the whole QGIS hangs.

**Comment by gkahiu** [comment] 2016-05-25 13:28
I cannot reproduce your issue, I have created 3 profiles separately, one after the other, and have not experienced any issue.
![wizard](https://cloud.githubusercontent.com/assets/3840267/15541554/b300f980-2295-11e6-903e-3eadfb6d5fe2.PNG)

@pgathogo, can you replicate the issue in your instance?

**Comment by wondie** [comment] 2016-05-25 15:09
That is good to know. So what I did to restart from scratch is, deleted stdm db, created stdm db, installed postgis to the db, removed all rows of configuration.stc except <Configuration version="1.2"> and its closing tag. Then when I restarted, I successfully created a profile but when I run it again, STDM and then QGIS freeze. Is there anything that I am missing in starting from scratch?

**Comment by gkahiu** [comment] 2016-05-26 06:50
Check your PostgreSQL logs immediately the system hangs; the logs are
under *[program
files folder]\PostgreSQL\9.x\data\pg_log*; the files have a date suffix
appended to the name so check for the correct date and open it to see if
there are any logged errors. If there is not sufficient detail in the
errors, then change the log mode in *postgresql.conf* (under the section
labeled ERROR REPORTING AND LOGGING ~line 293) to debug1 to debug5, see
more details here:
https://www.postgresql.org/docs/9.4/static/runtime-config-logging.html.
Remember to restart the PostgreSQL windows service for every change you
make in *postgresql.conf*.

All the best.

**Comment by wondie** [comment] 2016-05-26 07:00
Thank you for the useful info. I think the log shows where the problem is. Below is the last error log. 
```

2016-05-26 09:55:10 EAT ERROR:  constraint "tu_social_tenure_relationship_supporting_document_tu_supporting" for relation "tu_social_tenure_relationship_supporting_document" already exists
2016-05-26 09:55:10 EAT STATEMENT:  ALTER TABLE tu_social_tenure_relationship_supporting_document ADD CONSTRAINT tu_social_tenure_relationship_supporting_document_tu_supporting_doc_id_fkey FOREIGN KEY(tu_supporting_doc_id) REFERENCES tu_supporting_document (id)

```

**Comment by wondie** [comment] 2016-05-26 07:56
I got a more detailed error message below. 

```
'tu_social_tenure_relationship_supporting_document' ORDER BY f_geometry_column ASC
2016-05-26 10:48:50 EAT NOTICE:  identifier "tu_social_tenure_relationship_supporting_document_social_tenure_relationship_id_fkey" will be truncated to "tu_social_tenure_relationship_supporting_document_social_tenure"
2016-05-26 10:48:50 EAT STATEMENT:  ALTER TABLE tu_social_tenure_relationship_supporting_document ADD CONSTRAINT tu_social_tenure_relationship_supporting_document_social_tenure_relationship_id_fkey FOREIGN KEY(social_tenure_relationship_id) REFERENCES tu_social_tenure_relationship (id)
2016-05-26 10:48:50 EAT ERROR:  constraint "tu_social_tenure_relationship_supporting_document_social_tenure" for relation "tu_social_tenure_relationship_supporting_document" already exists
2016-05-26 10:48:50 EAT STATEMENT:  ALTER TABLE tu_social_tenure_relationship_supporting_document ADD CONSTRAINT tu_social_tenure_relationship_supporting_document_social_tenure_relationship_id_fkey FOREIGN KEY(social_tenure_relationship_id) REFERENCES tu_social_tenure_relationship (id)
2016-05-26 10:48:50 EAT NOTICE:  identifier "tu_social_tenure_relationship_supporting_document_tu_supporting_doc_id_fkey" will be truncated to "tu_social_tenure_relationship_supporting_document_tu_supporting"
2016-05-26 10:48:50 EAT STATEMENT:  ALTER TABLE tu_social_tenure_relationship_supporting_document ADD CONSTRAINT tu_social_tenure_relationship_supporting_document_tu_supporting_doc_id_fkey FOREIGN KEY(tu_supporting_doc_id) REFERENCES tu_supporting_document (id)
2016-05-26 10:48:50 EAT ERROR:  constraint "tu_social_tenure_relationship_supporting_document_tu_supporting" for relation "tu_social_tenure_relationship_supporting_document" already exists
2016-05-26 10:48:50 EAT STATEMENT:  ALTER TABLE tu_social_tenure_relationship_supporting_document ADD CONSTRAINT tu_social_tenure_relationship_supporting_document_tu_supporting_doc_id_fkey FOREIGN KEY(tu_supporting_doc_id) REFERENCES tu_supporting_document (id)
```

The error `2016-05-26 10:48:50 EAT ERROR:  constraint "tu_social_tenure_relationship_supporting_document_tu_supporting" for relation "tu_social_tenure_relationship_supporting_document" already exists` happened twice. 
I also tried to delete the table (drop cascade) but didn't fix the issue. Then I tried to delete the constraint and that made pgAdmin to hang.

**Comment by gkahiu** [comment] 2016-05-26 09:44
I cannot replicate the issue, I tried deleting some tables manually in
pgAdmin and successfully re-run the wizard so it still seems your database
has some sort of conflict with the constraints. PostgreSQL has a buffer
cache but accessing it is not straight forward so my only guess is that
there is a conflict with the data in the cache. Could you try working with
a new database but using a different db name, may be that way there will be
no reference to the cache. Otherwise, I cannot think of any other solution.

**Comment by wondie** [comment] 2016-05-26 10:32
I tried with a new database called stdm2. The wizard did run successfully with empty database. However, when I deleted a table and re-run the wizard, it hangs again.

**Comment by wondie** [comment] 2016-05-27 16:28
I then went to stdm3 database. Then came back to stdm database, deleted the existing data, enabled postgis extension and run the wizard. It worked, and when I re-run the wizard after making changes, the wizard completed successfully. Then I deleted spatial unit and party tables (Drop Cascade), and when I re-run the wizard it hangs again.

**Comment by gkahiu** [comment] 2016-05-28 08:15
Aah, now I see it in my setup as well. Let me look into it and revert.

**Comment by wondie** [comment] 2016-06-06 19:08
This issue is now fixed!

**Comment by wondie** [comment] 2016-06-09 12:21
This issue is back. When I delete a table in pgAdmin and run the wizard again. It hangs.

**Comment by gkahiu** [comment] 2016-06-09 12:25
Which specific table? Does the table participate in an STR relationship?
Does it have supporting documents enabled? More details will help.

**Comment by wondie** [comment] 2016-06-09 13:40
I tried a table participating in an STR relationship without supporting document and it still hangs.

**Comment by gkahiu** [comment] 2016-06-09 13:43
Send me the *configuration.stc* file that you are using, I recreate the
database and also the exact table name(s) that when deleted cause the
system to hang.

Regards,

John

**Comment by wondie** [comment] 2016-06-09 17:57
Ok cool. I have uploaded the config and database backup [here ](https://www.dropbox.com/home/Public?preview=configuration.stc) and [here](https://www.dropbox.com/home/Public?preview=stdm_Thu_09_06_2016.backup).

**Comment by gkahiu** [comment] 2016-06-10 02:26
I cannot access either file.

**Comment by wondie** [comment] 2016-06-10 06:15
Oh sorry. I have updated the links above.

**Closed** 2016-06-29 14:22 UTC
Labels: bug
