### ISSUE TITLE
Failed to Create STR

### ISSUE THREAD

**Issue by nkoech** [gltn/stdm#206] opened 2016-12-06 20:53 UTC
The error shows up when you click the _**Next**_ button on **_STR_** wizard window in the _**Supporting Documents**_ section. 

![str_error_1](https://cloud.githubusercontent.com/assets/8905226/20942962/bd7dd14a-bc0e-11e6-919b-23c349dc2513.png)

Below is a log error from PostgreSQL concerning the same issue

2016-12-06 23:10:36 EAT ERROR:  invalid input syntax for integer: "NDIII167" at character 314
2016-12-06 23:10:36 EAT STATEMENT:  `SELECT mi_paddy.id AS mi_paddy_id, mi_paddy.paddy_code AS mi_paddy_paddy_code, mi_paddy.location_name AS mi_paddy_location_name, mi_paddy.area AS mi_paddy_area, mi_paddy.subdivisions AS mi_paddy_subdivisions, ST_AsBinary(mi_paddy.spatial_geometry) AS mi_paddy_spatial_geometry 
	FROM mi_paddy 
	WHERE mi_paddy.id = 'NDIII167' 
	 LIMIT 1`

**Comment by gkahiu** [comment] 2016-12-07 00:12
@wondie this is a strange error. Could you liaise with Koech and check the format of the existing data in the db?
@nkoech could you please send the configuration and database backup?

**Comment by wondie** [comment] 2016-12-07 02:30
@gkahiu yes it is a strange error and I am surprised how this error was never seen before! 
The issue is most likely caused by an error of treating all relations parent tables as a lookup tables in [this function](https://github.com/gltn/stdm/blob/master/utils/util.py#L533).

@nkoech I will wait for the configuration and db backup? In the mean time, try to reproduce the issue again after replacing the util.py file located in stdm/utils folder with the one attached here. 
[util.zip](https://github.com/gltn/stdm/files/635515/util.zip)

@gkahiu I think we need to create a branch 1.4.3 so that we incorporate this and other issues and update the plugin repository.

**Comment by wondie** [comment] 2017-01-15 20:52
This issue is now fixed with [this commit](https://github.com/gltn/stdm/commit/e522aa24652da0a123fea1708acde70541ec3e23) and it is also incorporated in the upcoming STDM 1.5.

**Closed by wondie** 2017-01-15 20:52 UTC
Labels: bug
